### ISSUE TITLE
[ud] Release v1.3: pos mapping

### ISSUE THREAD

**Issue by makazhan** [ftyers/docs#12]
**Original e-mail:**
1. I've looked through the POS labels, and the following (in descending freq. order) are not specified among universals in ud:
- cop (ud has a relation but not pos-label);
- post;
- postadv;
- qst;
- cnjadv;
- mod_ass;
- mod;
- emph.
  Will the following ud mappings work:
- cop → VERB?
- post → ADP?
- qst → PART?
- cnjadv → CONJ/SCONJ (depending on context)?
- mod_ass (ғой and stuff) → PART?
- mod → ?
- emph (шы as in айтшы) → PART?

**Jonathan's reply:**

> - cop → VERB?

Hmm, my feeling is that this is wrong, at least when it's null.  Fran,
what do you think?

> - post → ADP?

Yes, that's good.

> - qst → PART?

Sure.

> - cnjadv → CONJ/SCONJ (depending on context)?

Probably.  Fran?

> - mod_ass (ғой and stuff) → PART?

Sure.

> - mod → ?

Probably VERB.

> - emph (шы as in айтшы) → PART?

Sure.

> We can postadv to ADV and heave a adv_type=adposition feature indicating
> that it is also an adposition (or vice versa).

Postadvs have nothing to do with adpositions or postpositions, or at
least that wasn't the intention.  I guess for the most part they're
dependent on noun phrases, so they're nothing like adverbs or
postposions.  I might just call these PART for now.  Fran?

**Comment by makazhan** [comment]
@jonorthwash

> > cop → VERB?
> 
> Hmm, my feeling is that this is wrong, at least when it's null. Fran,
> what do you think?

Last time I checked ud people were contemplating to [label copular verbs as aux](https://github.com/UniversalDependencies/docs/issues/275). This is just a general remark, but one to keep in mind.

My proposal on null copulas would be not to analyze them in detail, i.e. instead of:

```
...
47  алаланбауы    алала  _   v   tv|pass|neg|ger|px3sp|nom   48  csubj   _   _
48-49   тиіс    _   _   _   _   _   _   _   _
48  _   тиіс    _   adj _   0   root    _   _
49  _   е  _   cop aor|p3|sg   48  cop _   _
```

use something like:

```
...
47  алаланбауы    алала  _   v   tv|pass|neg|ger|px3sp|nom   48  csubj   _   _
48  тиіс    тиіс    ADJ <adj>+е<cop><aor><p3><sg>  aor|p3|sg   0   root    _   _
```

That is to acknowledge null copula in the fine-grained pos tag field by means of an Apertium tag and label overt copulas as VERB/AUX.

## 

> > mod → ?
> 
> Probably VERB.

How about these:

Ол әдемі/келетін [болған] _сияқты/көрінеді/білем_. (Here _білем_ is not a verb, but has its meaning smth. like _I reckon_ she is/was beautiful.)

How are those different from _шығар_ (marked as mod in your tb)? Particularly _сияқты_ which also agrees with the subject, but I'm hesitant to call it a verb.

## 

> Postadvs have nothing to do with adpositions or postpositions, or at
> least that wasn't the intention. I guess for the most part they're
> dependent on noun phrases, so they're nothing like adverbs or
> postposions. I might just call these PART for now. Fran?

Or they can depend on adjectives (жалғыз ғана), adverbs (жай ғана ашты), verbal forms (ашатын ғана, қарап қана қойды). I noticed that ғана is consistently tokenized as one token together with its head. However, you guys also have this:

```
...
10  келісімі    келісім  _   n   px3sp|nom   13  nmod    _   _
11-12   бойынша ғана _   _   _   _   _   _   _   _
11  _   бойынша  _   post    _   10  case    _   _
12  _   ғана    _   postadv _   10  advmod  _   _
13  қиылады  қи    _   v   tv|pass|aor|p3|sg   0   root    _   _
```

Notice how _ғана_ here depends on _келісімі_ not on _бойынша_.
So why is _бойынша ғана_ a single token then? Just asking:)
Also, how would _бойынша ғана емес_ be tokenized?
(I've tried apertium-kaz it groups the first two words and leaves out the last)

Also, _ғана_ accepts null-copula, as in _Біз әлі оқушы ғанамыз_

**Comment by ftyers** [comment]
About POS: 

```
cop; => VERB
post; => ADP
postadv; => ADV
qst; => PART
cnjadv; => SCONJ [definitely not CONJ]
mod_ass; => PART
mod; => PART
emph.  => PART
```

**Comment by jonorthwash** [comment]
> Ол әдемі/келетін [болған] _сияқты/көрінеді/білем_. (Here білем is not a verb, but has its meaning smth. like I reckon she is/was beautiful.)
> 
> How are those different from _шығар_ (marked as mod in your tb)? Particularly _сияқты_ which also agrees with the subject, but I'm hesitant to call it a verb.

I would say _шығар_ and _сияқты_ are "particles" in UD's terminology.  They come before copula and verbal agreement, right?  So _сен әдемі сияқты_сың__ and _сен келетін сияқты_сың__ ?

One other way to analyse these (assuming my examples are right?) would be to say сияқты is a predicate of some sort (either noun or adjective) and that it's the root with a copula relationship to the subject, which in this case would have to be clauses....  or something.  I'm not convinced `postadv` is right...

**Comment by jonorthwash** [comment]
@makazhan, it might be good to take whatever's left of this issue and make multiple new issues addressing each remaining issue.  It will be easier to close each one out separately.

**Comment by ftyers** [comment]
About ғана: 

The reason we have it tokenised as a single token with the preceding word (note, word not head) is because for generation you need to know both. as the underlying form is -Gана not -ғана. Our transducer goes both ways, allows both analysis, and proper generation, so in some cases we have to make some decisions which might seem a bit strange in order to get the proper surface form from an analysis.

**Comment by jonorthwash** [comment]
Are there any parts of this issue that weren't split out?  (Sorry, I missed that you'd split them out last week and only just saw them today when Fran alerted me to their presence.)  If there are no loose ends left in this particular issue, I guess we can probably close it out.

**Comment by makazhan** [comment]
@jonorthwash 

I overlooked `abbr`. In the initial conversion I mapped it to nouns, but it's not always true, of course. They'll have to be dealt with manually, I guess.

I'll open an issue for that anyway. Other than that, everything got split.

**Comment by jonorthwash** [comment]
Cool.
