### ISSUE TITLE
[ud] Release v1.3: pos mapping: qst => PART

### ISSUE THREAD

**Issue by makazhan** [ftyers/docs#14]
We all agree that _qst_ maps to PART in UD.

**Tokenization:**
We all agree that question particles are tokenized together with a preceding word.

**Dependency:**
We all agree that question particles subordinate to the head of a preceding phrase with relation **discourse**:

```
...
4-6 бар ма _   _   _   _   _   _   _   _
4   _   бар  _   adj _   0   root    _   _
5   _   е  _   cop aor|p3|sg   4   cop _   _
6   _   ма    PART    qst _   4   discourse   _   _
7   ?   ?   _   sent    _   4   punct   _   _
```

or (not in treebank):

```
...
1   келетін  кел  _   v   iv|gpr_impf 0   root    _   _
2-3 болған ба   _   _   _   _   _   _   _   _
2   _   бол  _    vaux   iv|past|p3|sg   1   aux _   _
3   _   ма    PART    qst _   1   discourse   _   _
4   ?   ?   _   sent    _   1   punct   _   _
```

**Comment by ftyers** [comment]
Yes, agree.

**Comment by makazhan** [comment]
**Closed class members:**
- MA;
- ше.

The last one is used like:

_Мен ше?_ (What about me?)

_Айтпасам ше?_ (What if I won't tell?)

They also do not permit anything in between themselves and their governors (except for auxiliaries and copulas)

Does this make sense?

**Comment by jonorthwash** [comment]
Sounds about right, yeah.
