### ISSUE TITLE
[ud] Release v1.3: pos mapping: post => ADP

### ISSUE THREAD

**Issue by makazhan** [ftyers/docs#15]
We all agree that _post_ maps to ADP in UD.

**Tokenization:**
We all agree that all "separate" postpositions are tokenized separately and that the following 
get split in the detailed analysis:
- abessive, sIz;
- munitative, LI;
- attributive ~time adverbs, GI.

_anything to add here?_

**Dependency:**
We all agree that regardless of tokenization and governor (nominal, verbal nouns/adjectives) postpositions subordinate with relation **case**:

``````
...
3-4 негізсіз    _   _   _   _   _   _   _   _
3   _   негіз  _   n   _   5   nmod    _   _
4   _   сыз  _   ADP _   3   case    _   _```
or (not in treebank):
``````

or:

```
...
6   болып  бол  _   v   iv|prc_perf 5   cop _   _
7   қалган    қал  _   vaux    ger_past|nom    5   aux _   _
8   соң  соң  _   ADP _   6   case    _   _
```

**Comment by makazhan** [comment]
attributive ~time adverbs, GI: taken from [here](http://wiki.apertium.org/wiki/Turkic_languages/Ki) :)

**Comment by makazhan** [comment]
Notice how in the last analysis I subordinated _соң_ to _болып_ (originally depended on _қалған_).
This is per UD [status of function words](http://universaldependencies.org/u/overview/syntax.html) that reads:

> The primacy of content words implies that function words normally do not have dependents of their own. In particular, it means that multiple function words related to the same content word always appear as siblings, never in a nested structure, regardless of their interpretation. A typical case is that of auxiliary verbs, which never depend on each other.

and:

> Negation can modify any function word, but other types of modifiers are disallowed for function words that express properties of the head word often expressed morphologically in other languages. This class, which we refer to as pure function words, includes auxiliary verbs, case markers (adposition), and articles, but needs to be defined explicitly for each language. When pure function words appear with modifiers other than negation, we take the modifier to apply to the entire phrase and therefore attaches it to the head word of the function word, as illustrated in the following example.

I will sum up cases (in the treebank) that do not satisfy this condition in a separate issue.

**Comment by ftyers** [comment]
I agree with this. We don't like that the `ADP` doesn't go to the word it morphologically depends on, but given the UD guidelines there isn't really a way around this. We also have some cases of auxiliary chaining that will probably need to be changed. Note that I suggest changing this now, but bringing it up at every available opportunity that it is better to be morphologically accurate here.

**Comment by makazhan** [comment]
Got it!

I close the issue.

Feel free to reopen.
