### ISSUE TITLE
[ud] Release v1.3: pos mapping: emph => PART

### ISSUE THREAD

**Issue by makazhan** [ftyers/docs#17]
We all agree that _emph_ maps to PART in UD.

**Closed class memebers**
- шЫ

_anything to add here?_

**Tokenization:**
We all agree that _emph_ are split in a detailed analysis.

**Dependency:**
We all agree that _emph_ subordinate to the verb it is attached to with relation **discourse**:

```
...
6-7 айтшы  _   _   _   _   _   _   _   _
6   _   айт  _   v   tv|imp|p2|sg    10  ccomp   _   _
7   _   шы    _   PART    _   6   discourse   _   _
```

**Comment by ftyers** [comment]
Agree.

**Comment by jonorthwash** [comment]
Yes, sounds great!
