### ISSUE TITLE
[ud] Release v1.3: pos mapping: cop => VERB

### ISSUE THREAD

**Issue by makazhan** [ftyers/docs#18]
1. Me and Francis agree that _cop_ maps to VERB in UD.
2. Jonathan had doubts about null copula being a verb.
3. There is an argument in UD discussion to treat copulas as [AUX](https://github.com/UniversalDependencies/docs/issues/275).

**Closed class memebers**
- е-;
- бол-.

_anything to add here?_

**Tokenization:**
Currently null copulas get a detailed analysis and overt ones are tokenized separately.

I proposed not to split out null copulas, but that was just a suggestion. I don't really mind splitting.

**Dependency:**
We all agree that _cop_ subordinate to the head of a corresponding predicate with relation **cop**:

```
...
1   Тіпті  тіпті  _   adv _   2   advmod  _   _
2-4 қымбат қой _   _   _   _   _   _   _   _
2   _   қымбат    _   adj _   0   root    _   _
3   _   е  _   VERB    aor|p3|sg   2   cop _   _
4   _   ғой  _   PART    _   2   discourse   _   _
5   !   !   _   sent    _   2   punct   _   _
```

or (not in treebank):

```
...
1   Тіпті  тіпті  _   adv _   2   advmod  _   _
2   қымбат    қымбат    _   adj _   0   root    _   _
3-4 екен ғой _   _   _   _   _   _   _   _
3   _   е  _   VERB    aor|evid|p3|sg  2   cop _   _
4   _   ғой  _   PART    _   2   discourse   _   _
5   !   !   _   sent    _   2   punct   _   _
```

**Comment by makazhan** [comment]
In the examples I tagged copulas as verbs regardless of surface realization.
Would everyone agree with such analysis?

Regarding VERB/AUX distinction, I kind of understood the point been made for English (see the link above), but I'm not sure it applies to Kazakh. The way we've been doing things verbal nouns and adjectives never had auxiliaries (only copulas) and verbal adverbs never had copulas (only auxiliaries).

Does this makes sense?

## 

So current proposal:
cop => VERB (regardless of surface);

**Comment by jonorthwash** [comment]
Yes, VERB, not AUX.  Because you can say something like "Тіпті қымбат болып жатыр" (right?), where what we're labelling as cop also has a dependent aux.

**Comment by ftyers** [comment]
Agree, verb.
