### ISSUE TITLE
[ud] Release v1.3: pos mapping: postadv => PART

### ISSUE THREAD

**Issue by makazhan** [ftyers/docs#19]
Based on our endorsements of [this comment](https://github.com/ftyers/docs/issues/13#issuecomment-211129520):

> So with postpositions it would be like this?
> (shorthand)
> 
> ```
> ...
> 3. үйге үй n.dat noun ...
> 4. қарай қарай postpos case 3
> ```
> 
> And with postadv like this:
> 
> ```
> ...
> 3. үйге үй n.dat noun ...
> 4. ғана ғана part advmod 3
> ```
> 
> It's kind of weird having a particle adverb-modding a noun...  But otherwise it's fairly consistent with what we do in our analyser, and unique enough that it'll be easy to identify and change if it's decided to do something different later.

we all agree that _postadv_ maps to PART in UD.

**Tokenization:**
Phonologically sensitive stuff is tokenized together otherwise separately.

**Dependency:**
We all agree that _postadv_ subordinate to the head of a preceding phrase with relation **advmod**:

```
...
1   Қандай    қандай    _   prn itg|sim 12  advcl   _   _
2-3 болғанда да   _   _   _   _   _   _   _   _
2   _   бол  _   v   iv|ger_past|loc 1   cop _   _
3   _   да    _   PART    _   2   advmod  _   _
```

or:

```
...
33  басқарушы  басқар    _   v   tv|gpr_pot  41  conj    _   _
34  емес    емес    _   PART    _   33  advmod  _   _
```

**Comment by jonorthwash** [comment]
Sounds good to me!
