### ISSUE TITLE
Subjects of passive verbs

### ISSUE THREAD

**Issue by ftyers** [ftyers/docs#4]
The UD guidelines allow for subjects of passive verbs to be explicitly marked:

```
Food is cooked by Erik.
nsubjpass(cooked, Food)
```

In the Apertium Kazakh treebank we do not mark subjects of passivised verbs differently to subjects of non-passivised verbs. This is because the state of being passive is trivially recoverable from the verbal morphology.

Furthermore, we are of the opinion that derivational verb valency realignment in Turkic is not something that can be adequately accounted for simply by introducing a new label for passives. We should also take into account causatives.

Compare for example:

    Мен балаға əнді тыңдаттым.

Does "Мен" or "балаға" get the subject relation here ?

**Comment by makazhan** [comment]
Agree on this account.
With causatives I would consider causer a subject and caused a direct object.

**Comment by ftyers** [comment]
But there would then be two subjects or two objects ?

```
nsubj(тыңдаттым, Мен)
nsubj(тыңдаттым, балаға)
dobj(тыңдаттым, əнді)
```

or:

```
nsubj(тыңдаттым, Мен)
dobj(тыңдаттым, балаға)
dobj(тыңдаттым, əнді)
```

Or something else?

**Comment by ftyers** [comment]
So, should the result be that we do not use the `nsubjpass` label for now. And we determine this by the morphology / valency of the verb ?

**Comment by jonorthwash** [comment]
That seems reasonable to me.  What about causative verbs?

**Comment by ftyers** [comment]
I think this should probably just be a question left for the next revision of the standard. In the meantime we can annotate the causative subjects as nmod or similar.

**Comment by jonorthwash** [comment]
Can we annotate them in a way so that we can find them again easily? :-P

**Comment by ftyers** [comment]
Well, in our treebank we could just make up language-specific subrelations, and then simplify them for the release. e.g. `nsubj:pass`, `nsubj:caus`  -> `nsubj`.

**Comment by jonorthwash** [comment]
That sounds good to me.

**Comment by jonorthwash** [comment]
Except that `nsubj:caus` → `nmod`, per your earlier comment?

**Comment by makazhan** [comment]
So, what's the consensus?
1. We obsolete `nsubj:pass`
2. We introduce `nsubj:caus`

**Comment by ftyers** [comment]
I think that we should probably obsolete both for now and bring this issue up with the wider UD community.

**Comment by jonorthwash** [comment]
So for now, causative verbs will typically have two subjects, as opposed to two objects? And passive subjects will be like other subjects?

**Comment by ftyers** [comment]
Ok, updated proposal (after discussion with Çağrı and Jonathan):

Intransitives:

Subject = `nsubj`

Transitives:

Subject = `nsubj`
Object = `dobj`

Causatives of intransitives:

Subject = `nsubj`
Object = `dobj`

Causatives of transitives:

Subject = `nsubj`
Causee = `nmod:caus`
Object = `dobj`

Passives of transitives:

Subject = `nsubj`

There is also the question of double causatives, but I don't think we have any of those in our treebanks.

**Comment by jonorthwash** [comment]
These seem okay for now.  As for double causatives, I think marking 2nd or 3rd "embedded subjects" (or whatever) as `nmod:caus` as well isn't a problem.  Once we have a treebank annotated this way, we can investigate if there's something else we can do with these, and if we decide to change them later on it should be a fairly trivial fix.

**Comment by makazhan** [comment]
That's a neat solution. Just an example of possible double causative usage (dep,gov):

```
1 Апам       my aunt
2 мені       me
3 хатты      a letter.ACC
4 көршіге    neighbor.DAT
5 оқытқызды  made made read
```

_My aunt made me to made the neighbor read a letter._
According to the proposal would it be analyzed as:
nsubj(1,5)
nmod:caus(2,5)
dobj(3,5)
nmod:caus(4,5)

**Comment by ftyers** [comment]
Ok, so let's implement this. 

https://github.com/ftyers/docs/blob/pages-source/_kk-dep/nmod-caus.md
